name: Repack Boot Image

on:
  workflow_dispatch:
    inputs:
      boot_url:
        description: "原始 boot.img 下载链接"
        required: true
      image_url:
        description: "新内核 image 文件下载链接"
        required: true

jobs:
  repack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download magiskboot
        run: |
          wget -O magiskboot https://github.com/Iconkop/awrule/releases/download/v2025.09.08.1810/magiskboot
          chmod +x magiskboot

      - name: Download original boot.img
        run: |
          wget -O boot.img "${{ github.event.inputs.boot_url }}"
          ls -lh boot.img

      - name: Download new kernel image
        run: |
          wget -O image "${{ github.event.inputs.image_url }}"
          ls -lh image

      - name: Unpack original boot.img
        run: |
          ./magiskboot unpack boot.img
          ls -lh

      - name: Replace kernel
        run: |
          cp image kernel
          echo "kernel replaced"

      - name: Repack boot.img
        run: |
          ./magiskboot repack boot.img
          mv new-boot.img repacked_boot.img
          ls -lh repacked_boot.img

      - name: Upload repacked boot.img
        uses: actions/upload-artifact@v4
        with:
          name: repacked-boot
          path: repacked_boot.img
